## Start ubuntu container and mount the current directory
version: "3"

services:
  ubuntu-devbox:
    # image: ubuntu:22.04
    build:
      context: .
      dockerfile: devenv.dockerfile
    volumes:
      - .:/app
      # - ./temp.ignore:/sys/class/thermal/thermal_zone0/temp:ro
      - ./temp.ignore:/temp:ro
    working_dir: /app
    tty: true
    command: ./bin/golang-custom-rpi-exporter-linux-arm64 -enable-textfile-collector
    # command: ./bin/golang-custom-rpi-exporter-linux-arm64 -enable-textfile-collector -disable-http-collector
