## Start ubuntu container and mount the current directory
version: "3"

services:
  ubuntu-devbox:
    # image: ubuntu:22.04
    build:
      context: .
      dockerfile: devenv.dockerfile
    volumes:
      - .:/app
      - ./dist/default_linux_arm64/golang-custom-rpi-exporter:/usr/local/bin/golang-custom-rpi-exporter
      # - ./temp.ignore:/sys/class/thermal/thermal_zone0/temp:ro
      - ./temp.ignore:/temp:ro
    environment:
      - HOSTNAME=DevContainer
    working_dir: /app
    tty: true
    command: /usr/local/bin/golang-custom-rpi-exporter -enable-textfile-collector
    # command: ./bin/golang-custom-rpi-exporter -enable-textfile-collector -disable-http-collector
