version: "3"

tasks:
  build:
    cmds:
      - GOOS="linux" GOARCH="arm64" go build -a -tags netgo -ldflags '-w -extldflags "-static"' -o ./bin/golang-custom-rpi-exporter-linux-arm64 .
      - docker compose build
    silent: false

  build-all-binaries:
    cmds:
      - rm -rf ./bin/*
      - ./compile.sh linux/arm64 linux/arm
    silent: false

  release:
    deps:
      - build-all-binaries
    cmds:
      - gh release create {{.CLI_ARGS}} ./bin/* --draft --generate-notes
    silent: false

  start:
    deps:
      - build
    cmds:
      - docker-compose up -d --force-recreate
    silent: false

  metrics:
    deps:
      - start
    cmds:
      - docker compose exec ubuntu-devbox curl http://localhost:8080/metrics
      - docker compose down

  down:
    cmds:
      - docker compose down --volumes
    silent: false

  attach:
    cmds:
      - docker compose exec ubuntu-devbox bash
    silent: false
