version: "3"

tasks:
  build:
    cmds:
      - GOOS="linux" GOARCH="arm64" go build -a -tags netgo -ldflags '-w -extldflags "-static"' -o ./bin/golang-custom-rpi-exporter .
      # - GOOS="darwin" GOARCH="arm64" go build -a -tags netgo -ldflags '-w -extldflags "-static"' -o ./bin/golang-custom-rpi-exporter-darwin .
      - docker compose build
    silent: true

  up:
    cmds:
      - docker-compose up -d --force-recreate
    silent: true

  start:
    deps:
      - build
      - up
    silent: true

  metrics:
    deps:
      - start
    cmds:
      - docker compose exec ubuntu-devbox curl http://localhost:8080/metrics
      - docker compose down

  down:
    cmds:
      - docker compose down --volumes
    silent: true

  attach:
    cmds:
      - docker compose exec ubuntu-devbox bash
    silent: true
