version: "3"

tasks:
  build:
    cmds:
      - goreleaser build --id default --snapshot --clean
      - docker compose build
    silent: false

  build-all-binaries:
    cmds:
      - goreleaser build --snapshot --clean
    silent: false

  release:
    deps:
      - build-all-binaries
    cmds:
      - goreleaser release --clean --auto-snapshot
    silent: false

  start:
    deps:
      - build
    cmds:
      - docker-compose up -d --force-recreate
    silent: false

  metrics:
    deps:
      - start
    cmds:
      - docker compose exec ubuntu-devbox curl http://localhost:8080/metrics
      - docker compose down

  down:
    cmds:
      - docker compose down --volumes
    silent: false

  attach:
    cmds:
      - docker compose exec ubuntu-devbox bash
    silent: false
