name: Build docker images

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     arch: ["arm/v6", "arm/v7", "arm64"]
    #   fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: |
            linux/arm/v6
            linux/arm/v7
            linux/arm64/v8
          build-args: |
            GO_VERSION=1.21
            ALPINE_VERSION=3.19
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
